apiVersion: batch/v1
kind: Job
metadata:
  name: count-job
spec:
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: centos-container
        image: centos
        command:
          - "bin/bash"
          - "-c"
          - "for i in 1 2 3 4 5 6 7 8 9 ; do echo $i; done"
      restartPolicy: Never
