apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  failedJobsHistoryLimit: 3
  sucessfulJobsHistoryLimit: 5
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: busybox
              name: hello
              command:
              - /bin/sh
              - -c
              - date ; echo hello from the k8s cluster
          restartPolicy: OnFailure