apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  labels:
    name: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql
      ports:
      - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          value: john
        - name: MYSQL_PASSWORD
          value: johnpassword
